
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programaINT_VALUE MINUS NEW_LINE PLUSlamda : \nprograma : sentencia\n         | sentencia NEW_LINE programa\n\nsentencia : INT_VALUE operand INT_VALUE\n\noperand : PLUS\n        | MINUS\n'
    
_lr_action_items = {'INT_VALUE':([0,4,5,6,7,],[3,3,9,-5,-6,]),'$end':([1,2,8,9,],[0,-2,-3,-4,]),'NEW_LINE':([2,9,],[4,-4,]),'PLUS':([3,],[6,]),'MINUS':([3,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,4,],[1,8,]),'sentencia':([0,4,],[2,2,]),'operand':([3,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('lamda -> <empty>','lamda',0,'p_lamda','parser_class.py',26),
  ('programa -> sentencia','programa',1,'p_programa','parser_class.py',33),
  ('programa -> sentencia NEW_LINE programa','programa',3,'p_programa','parser_class.py',34),
  ('sentencia -> INT_VALUE operand INT_VALUE','sentencia',3,'p_sentencia','parser_class.py',45),
  ('operand -> PLUS','operand',1,'p_operand','parser_class.py',53),
  ('operand -> MINUS','operand',1,'p_operand','parser_class.py',54),
]
