
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEleftUMINUSDIVIDE L_PAREN MINUS NUMBER PLUS R_PAREN SEMICOLON TIMESprogram : sentence SEMICOLON program\n| sentence : expresion SEMICOLONexpresion : expresion PLUS expresion\n| expresion MINUS expresion\n| expresion TIMES expresion\n| expresion DIVIDE expresionexpresion : MINUS expresion %prec UMINUSexpresion : L_PAREN expresion R_PARENexpresion : NUMBER'
    
_lr_action_items = {'$end':([0,1,7,15,],[-2,0,-2,-1,]),'MINUS':([0,3,4,5,6,7,9,10,11,12,13,14,16,17,18,19,20,],[4,10,4,4,-10,4,4,4,4,4,-8,10,-4,-5,-6,-7,-9,]),'L_PAREN':([0,4,5,7,9,10,11,12,],[5,5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,9,10,11,12,],[6,6,6,6,6,6,6,6,]),'SEMICOLON':([2,3,6,8,13,16,17,18,19,20,],[7,8,-10,-3,-8,-4,-5,-6,-7,-9,]),'PLUS':([3,6,13,14,16,17,18,19,20,],[9,-10,-8,9,-4,-5,-6,-7,-9,]),'TIMES':([3,6,13,14,16,17,18,19,20,],[11,-10,-8,11,11,11,-6,-7,-9,]),'DIVIDE':([3,6,13,14,16,17,18,19,20,],[12,-10,-8,12,12,12,-6,-7,-9,]),'R_PAREN':([6,13,14,16,17,18,19,20,],[-10,-8,20,-4,-5,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,7,],[1,15,]),'sentence':([0,7,],[2,2,]),'expresion':([0,4,5,7,9,10,11,12,],[3,13,14,3,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> sentence SEMICOLON program','program',3,'p_program','ejercicio_3.py',49),
  ('program -> <empty>','program',0,'p_program','ejercicio_3.py',50),
  ('sentence -> expresion SEMICOLON','sentence',2,'p_sentence','ejercicio_3.py',54),
  ('expresion -> expresion PLUS expresion','expresion',3,'p_expresion_binary','ejercicio_3.py',58),
  ('expresion -> expresion MINUS expresion','expresion',3,'p_expresion_binary','ejercicio_3.py',59),
  ('expresion -> expresion TIMES expresion','expresion',3,'p_expresion_binary','ejercicio_3.py',60),
  ('expresion -> expresion DIVIDE expresion','expresion',3,'p_expresion_binary','ejercicio_3.py',61),
  ('expresion -> MINUS expresion','expresion',2,'p_expresion_unary','ejercicio_3.py',72),
  ('expresion -> L_PAREN expresion R_PAREN','expresion',3,'p_expresion_paranthesis','ejercicio_3.py',76),
  ('expresion -> NUMBER','expresion',1,'p_expresion_value','ejercicio_3.py',79),
]
