
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUAL ID NUMBER SEMICOLONprograma : sentencia \n| sentencia programasentencia : ID EQUAL NUMBER SEMICOLON'
    
_lr_action_items = {'ID':([0,2,7,],[3,3,-3,]),'$end':([1,2,4,7,],[0,-1,-2,-3,]),'EQUAL':([3,],[5,]),'NUMBER':([5,],[6,]),'SEMICOLON':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,2,],[1,4,]),'sentencia':([0,2,],[2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> sentencia','programa',1,'p_programa','ejercicio_1.py',37),
  ('programa -> sentencia programa','programa',2,'p_programa','ejercicio_1.py',38),
  ('sentencia -> ID EQUAL NUMBER SEMICOLON','sentencia',4,'p_sentencia','ejercicio_1.py',44),
]
